//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDES___Office_Directory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDES_DirectoryEntities : DbContext
    {
        public SDES_DirectoryEntities()
            : base("name=SDES_DirectoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<group> groups { get; set; }
        public DbSet<hour> hours { get; set; }
        public DbSet<office> offices { get; set; }
        public DbSet<otherLocation> otherLocations { get; set; }
        public DbSet<social> socials { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<website> websites { get; set; }
    }
}
