//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDES___Office_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class office
    {
        public office()
        {
            this.hours = new HashSet<hour>();
            this.otherLocations = new HashSet<otherLocation>();
            this.socials = new HashSet<social>();
            this.staffs = new HashSet<staff>();
            this.websites = new HashSet<website>();
        }
    
        public int officeId { get; set; }
        public Nullable<int> groupId { get; set; }
        public string officeName { get; set; }
        public string officeAcronym { get; set; }
        public string officePhone { get; set; }
        public string officeFax { get; set; }
        public string officeEmail { get; set; }
        public Nullable<int> officeBox { get; set; }
        public string officeLocationBuilding { get; set; }
        public string officeLocationBuildingNum { get; set; }
        public string officeLocationRoomNum { get; set; }
        public bool offersPublicServices { get; set; }
    
        public virtual group group { get; set; }
        public virtual ICollection<hour> hours { get; set; }
        public virtual ICollection<otherLocation> otherLocations { get; set; }
        public virtual ICollection<social> socials { get; set; }
        public virtual ICollection<staff> staffs { get; set; }
        public virtual ICollection<website> websites { get; set; }
    }
}
