//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDES___Office_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class otherLocation
    {
        public int otherLocationId { get; set; }
        public int officeId { get; set; }
        public string otherLocationName { get; set; }
        public string otherLocationBuildingName { get; set; }
        public string otherLocationBuildingNum { get; set; }
        public string otherLocationRoomNum { get; set; }
        public string otherLocationPhone { get; set; }
        public string otherLocationFax { get; set; }
        public string otherLocationEmail { get; set; }
    
        public virtual office office { get; set; }
    }
}
