//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDES___Office_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class social
    {
        public int socialId { get; set; }
        public int officeId { get; set; }
        public string socialName { get; set; }
        public string socialUri { get; set; }
        public string socialHandle { get; set; }
    
        public virtual office office { get; set; }
    }
}
