//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDES___Office_Directory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class website
    {
        public int websiteId { get; set; }
        public int officeId { get; set; }
        public string websiteName { get; set; }
        public string websiteUri { get; set; }
        public Nullable<int> websiteCal { get; set; }
        public int websiteOrder { get; set; }
    
        public virtual office office { get; set; }
    }
}
